### ISSUE TITLE
Introduce hotfix version v0.8.2 with crash fixes ahead of v0.9.0

### ISSUE THREAD

**Issue by Cliabhach** [fuzz-productions/CutoutViewIndicator#75]
@nononoah I'd like your input - I'm planning to tag a new release with fixes for issues #71 and #73 later today.

Should I push the remaining v0.9.0 bugs off to e.g. v0.10.0 and tag the build as v0.9.0?
Or perhaps that would be misleading and the build should be v0.8.2?

**Comment by Cliabhach** [comment]
For now, I'll make a v0.8.2 build with the changes. At least that'll let downstream consumers make use of it.

**Comment by nononoah** [comment]
Though the decision has been made, I'll nevertheless note that my suggestion would have matched the course you decided on.

**Comment by Cliabhach** [comment]
Right, then. I think we can close this issue now.
